# Generated by Django 5.2.6 on 2026-01-01 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='service.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Full description for the details page'),
        ),
        migrations.AddField(
            model_name='service',
            name='technologies',
            field=models.TextField(blank=True, help_text='Comma-separated list of technologies (e.g., Python, Django, React)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Short description for the home page'),
        ),
    ]
