# Generated by Django 5.2.6 on 2026-01-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('story', models.TextField(help_text='Our Story')),
                ('mission', models.TextField(help_text='Our Mission')),
                ('vision', models.TextField(help_text='Our Vision')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
            options={
                'verbose_name_plural': 'Company Profile',
            },
        ),
    ]
