# Generated by Django 5.2.6 on 2026-01-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_clientlogo_faq_pricingplan_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
