# Generated by Django 5.2.6 on 2026-01-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_chatmessage_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='tech/')),
                ('website_url', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='officeinfo',
            name='booking_url',
            field=models.URLField(blank=True, help_text='Calendly or Meeting URL'),
        ),
    ]
